version: '3.9'
services:
  php:
    build: ./infra/php
    volumes:
      - ./app/backend:/data
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./app/backend:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data